### ISSUE TITLE
Queue size never get full

### ISSUE THREAD

**Issue by danieldias51** [shettyh/threadpool#4]
Hey,

I was trying this lib and found out a small issue. The queue buffer size doesn't work as expected for low values. 
For example I've some tasks that I want to run but I don't want to allow more than let's say 2 jobs on the queue. After that I want to refuse and return an error saying that the queue is already full. 

So on the first place, the current implementation doesn't allow me to return an error if the queue gets full, since both methods `Execute` and `ExecuteFuture` just push the job to the queue channel and if the channel gets full the caller would just block.

Besides that, the queue never gets full, I created a threadpool with a job queue with the size 1 and called multiple times the `Execute`/`ExecuteFuture` but the queue never gets full. 
The dispatch method is always reading from the queue and fanning out a go routine with the job. Instead of holding the jobs on the queue, you are fanning out go routines holding the job and waiting for a worker.

Thoughts?

**Comment by shettyh** [comment]
@danieldias51 thanks for reporting the issue. I will look into it

**Comment by shettyh** [comment]
@danieldias51  fixed the issue. Please verify and close the issue if it is working

**Comment by danieldias51** [comment]
Yup, nice one, thank you
